### ISSUE TITLE
NOPE Proxy tab does not appear in Burp 2.0.16beta

### ISSUE THREAD

**Issue by 7a** [summitt/Burp-Non-HTTP-Extension#32] opened 2019-02-19 12:55 UTC
Could you please investigate why the NOPE Proxy tab does *not* appear in Burp 2.0.16beta?
It used to appear in earlier betas such as Burp 2.0.8beta.

Thanks!

**Comment by NavjotSinghMinhas** [comment] 2019-12-17 04:43
Do you have the link for Burp 2.0.8 Beta? :)

**Comment by 7a** [comment] 2019-12-18 15:21
At this stage, it's no longer beta, please just make it work on the latest Burp version, thank you :)

**Comment by 1110001** [comment] 2020-02-05 06:07
> At this stage, it's no longer beta, please just make it work on the latest Burp version, thank you :)

Did you get any solution? I am having the same issue.

**Comment by ilmanuz** [comment] 2020-07-23 09:58
Chances are the issue is related to the jvm you use. I was in the same situation and I solved by explicitly launching burp with an older jvm (Java SE 8) than the one my system was picking by default. After that the nope tab re-appeared.

**Comment by summitt** [comment] 2020-08-15 09:05
The changes have been merged from @jfish7 that mitigates this issue with newer versions of BURP

**Closed by summitt** 2020-08-15 09:05 UTC
